version: '3'

services:
  demo-lidarhd:
    container_name: demo-lidarhd
    command: python3 run_prod.py
    build:
      context: "."  
      dockerfile: Dockerfile
      args:    
        - http_proxy
        - https_proxy
    environment:
      - ACCESS_KEY_ID_RO=${S3_RO_ACCESS_KEY}
      - SECRET_ACCESS_KEY_RO=${S3_RO_PRIVATE_KEY}
      - ACCESS_KEY_ID_RW=${S3_RW_ACCESS_KEY}
      - SECRET_ACCESS_KEY_RW=${S3_RW_PRIVATE_KEY}
      - DEFAULT_BUCKET=${BUCKET}
      - ENDPOINT=${ENDPOINT}
      - REGION=${REGION}
      - HOST_SERVEUR=${HOST_SERVEUR}
    ports:
      - '5000:5000'
    restart: on-failure

  # CronJob en cible : https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
  # cron-lidarhd:
  #   container_name: cron-lidarhd
  #   command: python3 /usr/src/app/dalle_lidar.py
  #   build:  
  #     context: "."  
  #     dockerfile: Dockerfile
  #   restart: on-failure
